<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e20</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e82</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e15</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e67</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e29</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e37</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
