<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e60</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e25</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e72</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e38</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e44</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e43</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
