<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e1</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e68</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e24</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e77</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e20</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e56</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
