<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e67</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e57</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e83</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e19</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e59</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e44</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
