<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e7</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e62</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e77</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e14</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e59</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e47</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
