<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e16</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e45</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e17</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e76</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e66</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e3</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
