<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e18</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e58</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e50</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e64</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e79</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e42</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
