<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e19</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e40</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e55</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e10</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e78</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e38</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
