<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e41</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e15</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e19</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e25</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e13</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e78</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
