<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e38</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e54</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e21</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e54</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e53</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e69</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
