<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e38</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e20</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e60</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e36</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e13</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e78</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
