<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e5</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e22</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e58</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e42</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e76</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e10</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
