<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e39</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e10</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e47</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e33</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e53</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e65</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
