<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e31</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e56</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e13</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e37</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e32</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e72</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
