<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e63</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e71</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e8</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e29</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e62</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e50</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
