<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e40</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e64</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e66</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e36</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e14</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e32</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
