<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e43</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e56</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e52</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e50</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e84</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e35</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
