<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e20</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e27</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e17</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e33</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e10</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e13</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
