<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e4</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e65</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e38</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e60</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e75</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e39</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
