<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e18</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e66</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e20</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e52</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e41</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e26</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
