<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e15</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e73</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e44</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e8</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e78</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e69</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
