<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e55</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e78</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e36</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e69</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e77</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e12</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
