<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e13</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e41</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e35</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e32</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e70</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e12</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
