<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e32</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e35</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e14</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e23</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e22</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e18</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
