<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e38</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e72</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e41</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e77</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e42</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e35</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
