<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e62</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e52</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e71</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e44</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e31</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e57</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
