<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e50</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e68</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e75</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e51</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e69</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e34</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
