<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e51</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e50</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e65</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e23</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e57</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e83</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
