<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e34</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e59</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e61</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e68</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e35</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e44</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
