<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e57</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e80</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e32</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e71</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e26</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e11</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
