<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e60</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e42</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e84</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e70</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e11</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e42</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
