<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e27</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e20</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e8</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e16</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e37</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e17</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
