<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e10</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e30</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e23</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e68</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e66</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e43</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
