<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e23</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e39</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e73</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e41</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e36</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e65</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
