<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e63</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e76</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e12</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e23</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e25</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e45</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
