<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e49</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e78</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e15</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e48</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e32</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e63</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
