<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e19</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e9</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e36</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e18</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e71</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e68</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
