<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e20</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e63</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e73</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e36</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e29</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e32</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
