<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e42</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e57</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e40</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e39</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e45</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e34</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
