<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e63</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e82</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e43</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e26</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e20</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e14</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
