<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e45</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e32</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e69</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e67</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e33</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e54</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
