<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e42</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e39</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e20</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e69</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e56</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e83</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
