<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e49</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e76</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e34</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e79</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e60</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e66</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
