<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e12</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e31</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e43</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e25</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e68</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e53</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
