<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e69</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e42</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e74</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e41</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e67</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e51</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
