<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e47</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e84</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e16</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e58</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e53</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e64</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
