<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e37</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e24</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e72</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e46</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e53</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e18</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
