<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e17</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e58</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e17</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e48</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e15</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e74</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
