<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e68</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e36</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e12</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e78</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e59</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e76</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
