<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e35</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e17</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e41</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e62</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e43</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e48</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
