<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestCase>
    <Step>
        <EventId>e1</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e60</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e36</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e17</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e73</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
    <Step>
        <EventId>e23</EventId>
        <ReachingStep>false</ReachingStep>
    </Step>
</TestCase>
