//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.03 at 04:08:28 PM EDT 
//


package edu.umd.cs.guitar.model.data;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EventSequenceSetType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EventSequenceSetType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EventSequence" type="{}EventSequenceType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EventSequenceSetType", propOrder = {
    "eventSequence"
})
public class EventSequenceSetType {

    @XmlElement(name = "EventSequence")
    protected List<EventSequenceType> eventSequence;

    /**
     * Gets the value of the eventSequence property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eventSequence property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEventSequence().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EventSequenceType }
     * 
     * 
     */
    public List<EventSequenceType> getEventSequence() {
        if (eventSequence == null) {
            eventSequence = new ArrayList<EventSequenceType>();
        }
        return this.eventSequence;
    }

    /**
     * Sets the value of the eventSequence property.
     * 
     * @param eventSequence
     *     allowed object is
     *     {@link EventSequenceType }
     *     
     */
    public void setEventSequence(List<EventSequenceType> eventSequence) {
        this.eventSequence = eventSequence;
    }

}
