//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.26 at 05:34:08 PM EDT 
//


package edu.umd.cs.guitar.model.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InitialEventSet" type="{}EventSetType"/>
 *         &lt;element name="EventEffectSet" type="{}EventEffectSetType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "initialEventSet",
    "eventEffectSet"
})
@XmlRootElement(name = "EventTrace")
public class EventTrace {

    @XmlElement(name = "InitialEventSet", required = true)
    protected EventSetType initialEventSet;
    @XmlElement(name = "EventEffectSet", required = true)
    protected EventEffectSetType eventEffectSet;

    /**
     * Gets the value of the initialEventSet property.
     * 
     * @return
     *     possible object is
     *     {@link EventSetType }
     *     
     */
    public EventSetType getInitialEventSet() {
        return initialEventSet;
    }

    /**
     * Sets the value of the initialEventSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventSetType }
     *     
     */
    public void setInitialEventSet(EventSetType value) {
        this.initialEventSet = value;
    }

    /**
     * Gets the value of the eventEffectSet property.
     * 
     * @return
     *     possible object is
     *     {@link EventEffectSetType }
     *     
     */
    public EventEffectSetType getEventEffectSet() {
        return eventEffectSet;
    }

    /**
     * Sets the value of the eventEffectSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventEffectSetType }
     *     
     */
    public void setEventEffectSet(EventEffectSetType value) {
        this.eventEffectSet = value;
    }

}
