//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.26 at 05:34:08 PM EDT 
//


package edu.umd.cs.guitar.model.data;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EventStateSetType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EventStateSetType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EventState" type="{}EventStateType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EventStateSetType", propOrder = {
    "eventState"
})
public class EventStateSetType {

    @XmlElement(name = "EventState")
    protected List<EventStateType> eventState;

    /**
     * Gets the value of the eventState property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eventState property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEventState().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EventStateType }
     * 
     * 
     */
    public List<EventStateType> getEventState() {
        if (eventState == null) {
            eventState = new ArrayList<EventStateType>();
        }
        return this.eventState;
    }

    /**
     * Sets the value of the eventState property.
     * 
     * @param eventState
     *     allowed object is
     *     {@link EventStateType }
     *     
     */
    public void setEventState(List<EventStateType> eventState) {
        this.eventState = eventState;
    }

}
