//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.03 at 04:08:28 PM EDT 
//


package edu.umd.cs.guitar.model.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TestDataElement" type="{}TestDataElementType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "testDataElement"
})
@XmlRootElement(name = "TestData")
public class TestData {

    @XmlElement(name = "TestDataElement", required = true)
    protected TestDataElementType testDataElement;

    /**
     * Gets the value of the testDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link TestDataElementType }
     *     
     */
    public TestDataElementType getTestDataElement() {
        return testDataElement;
    }

    /**
     * Sets the value of the testDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestDataElementType }
     *     
     */
    public void setTestDataElement(TestDataElementType value) {
        this.testDataElement = value;
    }

}
